-- PostgreSQL Production Database Schema for Apex Pharma Logistics
-- Domain Architecture: Clinical Diagnostics & LIS Telemetry (healthcare)
-- Generated by BizzMitra AI Engine
-- Problem Statement Reference:
-- "Manual temperature logging and disconnected supplier manifests cause compliance audit failures and an 18% spoilage rate of sensitive biopharma shipments across multi-hop transit routes. 1. Real-time IoT temperature telemetry ingestion with automated threshold alerts. 2. Sub-second compliance audit reporting for FDA and ISO certifications. 3. Cut transit inventory spoilage to under 1.5%."

CREATE TABLE IF NOT EXISTS public.healthcare_records (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  col1_data TEXT NOT NULL, -- Semantic Mapping: Test Investigation Panel
  col2_data TEXT NOT NULL, -- Semantic Mapping: Analyzer Instrument ID
  status TEXT NOT NULL,    -- Semantic Mapping: Laboratory Stage
  badge TEXT DEFAULT 'Active',
  assignee TEXT NOT NULL,  -- Semantic Mapping: Pathologist Lead
  metric_value TEXT NOT NULL, -- Semantic Mapping: Report TAT SLA
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.healthcare_records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read-write for demo application"
  ON public.healthcare_records
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- Team and Role Authentication table
CREATE TABLE IF NOT EXISTS public.healthcare_users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL,
  badge TEXT NOT NULL,
  department TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.healthcare_users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read-write for authenticated users"
  ON public.healthcare_users
  FOR ALL
  USING (true)
  WITH CHECK (true);
